version: "3.9"
services:
  site:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    restart: always
    volumes:
      - ./:/site
    env_file:
      - ./.env
    ports:
      - 3000:3000
